modLoader="javafml"
loaderVersion="${loader_version}"
issueTrackerURL="https://github.com/mekanism/Mekanism/issues"
license="MIT"

[[mods]]
    modId="mekanism"
    version="${version}"
    displayName="Mekanism"
    displayURL="https://aidancbrady.com/mekanism/"
    authors="Aidancbrady, Thommy101, Thiakil, pupnewfster, dizzyd"
    credits="unpairedbracket, CyanideX, Ridanisaurus and many others"
    logoFile="logo.png"
    description='''Mekanism is a Minecraft add-on featuring high-tech machinery that can be used to create powerful tools, armor, and weapons.'''

[[dependencies.mekanism]]
    modId="minecraft"
    type="required"
    versionRange="${mc_version}"
    side="BOTH"
[[dependencies.mekanism]]
    modId="neoforge"
    type="required"
    versionRange="${forge_version}"
    side="BOTH"

[[dependencies.mekanism]]
    modId="appmek"
    type="incompatible"
    reason="Requires an update to support changes to Mekanism's Chemical API"
    versionRange="[,1.6.0-alpha.2]"
    side="BOTH"
[[dependencies.mekanism]]
    modId="enderio_conduits_modded"
    type="incompatible"
    reason="Requires an update to support changes to Mekanism's Chemical API"
    versionRange="[,6.0.24.351-nightly+d8261275]"
    side="BOTH"
[[dependencies.mekanism]]
    modId="laserio"
    type="incompatible"
    reason="Requires an update to support changes to Mekanism's Chemical API"
    versionRange="[,1.9.9]"
    side="BOTH"
[[dependencies.mekanism]]
    modId="jaopca"
    type="incompatible"
    reason="Requires an update to support changes to Mekanism's Chemical API"
    versionRange="[,5.0.1.2]"
    side="BOTH"