name: "Run Game Tests"

on:
  push:
    branches: [ "1.21.x" ]
  pull_request:
    branches: [ "1.21.x" ]
    types:
      - synchronize
      - opened
      - ready_for_review
      - reopened
    paths:
      - '**.java'

jobs:
  test:
    name: Game Tests
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v3
        with:
          cache-encryption-key: ${{ secrets.GRADLE_ENCRYPTION_KEY }}

      - name: Run Game Tests with Gradle
        run: ./gradlew runGameTestServer

      - name: Run Unit Tests with Gradle
        run: ./gradlew testJunit