# This workflow will build a package using Gradle and then publish it to the usual places

name: Build & Publish

on:
  push:
    branches:
      - 'release/**'

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Find last successful build
      id: last_success_build
      uses: SamhammerAG/last-successful-build-action@v4
      with:
        workflow: ${{github.workflow}}
        token: ${{github.token}}
        #verify ensures that it's reachable on the current branch
        verify: true
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      uses: gradle/gradle-build-action@v2
      with:
        arguments: clean build outputChangelog
        gradle-version: wrapper

    - name: Upload to workflow artifacts
      uses: actions/upload-artifact@v3
      with:
        path: |
          build/libs/
          build/changelog.html

#    - name: Publish
#      uses: gradle/gradle-build-action@v2
#      with:
#        arguments: curseforge modrinth publish
#        gradle-version: wrapper
#      env:
#        CURSEFORGE_KEY: ${{ secrets.CURSEFORGE_KEY }}
#        MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
#        MEK_MAVEN_PW: ${{ secrets.MEK_MAVEN_PW }}
#        BUILD_NUMBER: ${{ github.run_id }}
#        GIT_COMMIT: ${{ github.sha }}
#        GIT_PREVIOUS_SUCCESSFUL_COMMIT: ${{ steps.last_success_build.outputs.sha }}
